LD - RequestType Service and Exception
ucsb-cs156-f24/proj-rec-f24-07 pull request #44
Opened 2024-11-18 09:00 UTC by lodetrick

Dependent on Issue #42 

### Description:
 - This PR creates a service for Request Type, that only saves a type if it is unique within the repository.
 - It also creates an exception, `EntityAlreadyExistsException` that is thrown by the service if the type already exists within the repository.
 - Creates the `ExampleApplicationRunner` class which saves hardcoded RequestTypes into the repository
 - Attempting to save a duplicate RequestType string will result in a BadRequest Error, returning a custom EntityAlreadyExistsException.

### Tests:
 - Needs RequestType entity and repository classes in the codebase, will rerun tests once #42 merged
 - All Tests Pass

### Issues:
 - Closes #43

2024-11-18 21:36 UTC, eug-wong submitted a review, later dismissed
LGTM!

2024-11-21 06:10 UTC, kanav9063 submitted a review, later dismissed
Changes for Request Type Serve and its tests seem correctly implemented

2024-11-24 02:33 UTC, pconrad requested changes
This is ok, but it can be made much simpler.  See comments on code review.

2024-11-24 02:33 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/rec/services/RequestTypeService.java
> +	public RequestType trySave(RequestType requestType) throws EntityAlreadyExistsException {
You don't need to get ALL of the request types and iterate through them.  Let the database do the work for you.

Instead, add a method to the RequestTypeRepository called 

```java
  Optional<RequestType> findByRequestType(String requestType);
```

Just look up the RequestType and see if it exists.  If it does, it's a duplicate. If not, it isn't.

Any time you are "looping through database records" looking for something, you should stop and say: wait... there's probably a better way.

2024-11-24 02:33 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/rec/services/RequestTypeService.java
> +		});
This code can be greatly simplified by using 

```java
Optional<RequestType> findByRequestType(String requestType);
```

2024-11-25 23:51 UTC, divyagsubramonian approved these changes
LGTM! The code focuses on handling and storing unique request types. A new exception was created (to handle repeated request types).

2024-11-26 05:27 UTC, pconrad approved these changes
LGTM!

2024-11-26 05:28 UTC, merged