EW - Remove Restaurants Backend and Frontend
ucsb-cs156-f24/proj-rec-f24-07 pull request #54
Opened 2024-11-20 01:39 UTC by eug-wong

**Description:**
- This PR removes Restaurants from the Navbar, as well as all relevant frontend files for creating, editing, and indexing Restaurants.
- Modifies Navbar test cases to test Placeholder instead

**Tests:**
- Passes all tests, including mutation tests

Closes #18

2024-11-21 00:19 UTC, divyagsubramonian commented
LGTM! All the files tied to Restaurants were deleted and changes to corresponding files (NavBar) were made accordingly.

2024-11-21 00:21 UTC, divyagsubramonian approved these changes
LGTM! All the files tied to Restaurants were deleted and changes to corresponding files (NavBar) were made accordingly.

2024-11-22 01:21 UTC, Ramon-W commented
Manually approved pending UI Tests.

2024-11-24 05:20 UTC, pconrad approved these changes
LGTM

2024-11-24 05:53 UTC, pconrad commented
To fix the testing gaps in this PR, see: 

https://ucsb-cs156-f24.slack.com/archives/C080JHJN9QE/p1732427414430999

2024-11-24 07:02 UTC, pconrad commented
When you remove both the Restaurant *and* the UCSBDates backend, it creates test coverage gaps that need to be fixed.

I took care of the merge conflicts for you (which I probably shouldn't have done—but I was being nice).  But as a result, the problem is now exposed.

Here's a solution that works.

https://ucsb-cs156-f24.slack.com/archives/C080JHJN9QE/p1732427414430999

2024-11-26 19:50 UTC, kanav9063 approved these changes
correctly made changes based on professors advice to remove Restaurants Backend and Frontend

2024-11-26 21:05 UTC, pconrad requested changes
One small change needed: `DummyController.java` goes under `test` , not `main`

2024-11-26 21:05 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/rec/controllers/DummyController.java
> +}
This file should be placed under `src/test/java/edu/ucsb/cs156/rec/controllers/DummyController.java` not `src/main/java/edu/ucsb/cs156/rec/controllers/DummyController.java`

2024-11-26 21:34 UTC, divyagsubramonian submitted a review, later dismissed
Looks good! DummyController was moved to the correct directory.

2024-11-27 19:09 UTC, pconrad submitted a review, later dismissed
LGTM

2024-11-29 22:45 UTC, merged