ds - updated rr controller and tests
ucsb-cs156-f24/proj-rec-f24-07 pull request #59
Opened 2024-11-20 19:11 UTC by divyagsubramonian

### Description:
- There are endpoints for each of the CRUD actions necessary to create, read, update, and delete a recommendation request that have been tested on swagger
  - GET api/recommendationrequest/{id}
  - PUT api/recommendationrequest/{id}
  - DELETE api/recommendationrequest/{id}
  - POST api/recommendationrequest/post

### Tests:
 - Passes all tests (NOT TESTED YET)

### Related Issues:
 - Dependent on #24 and #25 
 - Closes #28 
 - Closes #30

2024-11-22 22:18 UTC, lodetrick approved these changes
LGTM! I can see all the fields, and the tests look good. We might want to create an issue later to get rid of the name fields and replace those with user api calls, but other than that it looks good!

2024-11-26 05:43 UTC, pconrad requested changes
It does not appear that the author has taken the time to think through the  user stories involved here.  It is *so important* to keep the end user in mind, and what their *goal* is.

It is also important to really think carefully about the user *should* be able to do, and what they *should not* be able to do.

Read through the code, and the comments, and go BACK to the original issues (not the ones written up by the team, which contain many misunderstandings.)

2024-11-26 05:43 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/rec/controllers/RecommendationRequestController.java
> +    }
No... if this endpoint is for ROLE_USER it should look up the id of the current user and the return ONLY the recommendation requests for THIS user.  Not a findAll but a findByUserId(currentUser.getId())

2024-11-26 05:43 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/rec/controllers/RecommendationRequestController.java
> +    @PreAuthorize("hasRole('ROLE_ADMIN')")
No.  Requests are created by users, not admins.

2024-11-26 05:43 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/rec/controllers/RecommendationRequestController.java
> +    @PreAuthorize("hasRole('ROLE_ADMIN')")
```suggestion
    @PreAuthorize("hasRole('ROLE_USER')")
```

2024-11-26 05:43 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/rec/controllers/RecommendationRequestController.java
> +            @Parameter(name="requesterName") @RequestParam String requesterName,
No. You should get the currentUser.getId() and then set the requesterId inside the controller method.(there should NOT be a database field for requesterEmail or requesterName, only requestId).

2024-11-26 05:43 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/rec/controllers/RecommendationRequestController.java
> +            @Parameter(name="submissionDate", description="date (in iso format, e.g. YYYY-mm-ddTHH:MM:SS; see https://en.wikipedia.org/wiki/ISO_8601)") @RequestParam("submissionDate") @DateTimeFormat
No.  The submission date should be set inside the controller from a call to get the current date and time, or better yet, using the methods described here:

https://ucsb-cs156.github.io/topics/spring_boot/spring_boot_database.html#timestamps-on-database-rows

2024-11-26 05:43 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/rec/controllers/RecommendationRequestController.java
> +            @Parameter(name="professorName") @RequestParam String professorName,
No.  The userId of the professsor should be passed in via a dropdown menu that shows all users in the users database that have the professor role.  From that, we can get the email and name of the professor.

2024-11-26 05:43 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/rec/controllers/RecommendationRequestController.java
> +        // log.info("dateNeeded={}", dateNeeded);
Why are these commented out lines still in a PR that has been marked as Ready-For-Staff?

https://ucsb-cs156.github.io/topics/code_reviews/commented_out_code.html#why-should-commented-out-code-be-removed

2024-11-26 05:43 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/rec/controllers/RecommendationRequestController.java
> +        recommendationRequest.setStatus(status);
Status should be hard coded as `pending` on a newly created request.  The end user doesn't get to "choose" what status a new request is in.  It is *always* in the pending state, and only the professor gets to change it to either `accepted` or `denied`

2024-11-26 05:43 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/rec/controllers/RecommendationRequestController.java
> +        recommendationRequest.setCompletionDate(completionDate);
This should be left as null until the PROFESSOR marks it as complete, and then it should be set to the date on which that happens.

2024-11-26 05:43 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/rec/controllers/RecommendationRequestController.java
> +        recommendationRequest.setSubmissionDate(submissionDate);
This should be set to current date/time or else set using the @CreatedDate annotation

2024-11-26 05:43 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/rec/controllers/RecommendationRequestController.java
> +        recommendationRequest.setProfessorName(professorName);
Why is there still a professorEmail and professorName field? This should be replaced with professorId

2024-11-26 05:43 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/rec/controllers/RecommendationRequestController.java
> +        recommendationRequest.setRequesterName(requesterName);
Why is there still a requesterEmail and requesterName field?  This should be replaced with requesterId.

2024-11-26 05:43 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/rec/controllers/RecommendationRequestController.java
> +    }
You *also* need to see if this recommendation request belongs to this user!  They should NOT be able to see requests that are for other students.

2024-11-26 05:43 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/rec/controllers/RecommendationRequestController.java
> +    }
Users (not just admins) should be able to delete their OWN (but only their own) requests.  Please adjust the authorization, and add a check not just that the id is in the database, but also that the requesterId matches the currentUser.getId().

2024-11-26 05:43 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/rec/controllers/RecommendationRequestController.java
> +    @PreAuthorize("hasRole('ROLE_ADMIN')")
Users should be able to update their own request, and admins actually should NOT be able to.

But only their own requests, and only the details field, NOTHING ELSE.

2024-11-27 09:14 UTC, closed without merging