Form Component for RecommendationRequest plus tests
ucsb-cs156-f24/proj-rec-f24-07 pull request #61
Opened 2024-11-21 02:49 UTC by kanav9063

2024-11-22 01:33 UTC, lodetrick approved these changes
LGTM! I see that you included fixtures, so as long as that isn't a merge conflict it should be good. Once the RequestType dropdown is complete we can also add that in a later PR

2024-11-24 05:30 UTC, pconrad commented on frontend/src/main/components/RecommendationRequest/RecommendationRequestForm.js
> +        {/* Requester Email */}
No.  This should be replaced with a dropdown component that shows all users from the Users table that have the Professor role. 

The dropdown should show the professors name and email, and the value field should be the id of the selected professor.

2024-11-24 05:41 UTC, pconrad requested changes
This form needs some significant revisions.

2024-11-24 05:41 UTC, pconrad commented on frontend/src/main/components/RecommendationRequest/RecommendationRequestForm.js
> +        </Col>
No.  The requster id is set in the backend, so there is no need to enter it.  The currently logged in user's email and name are already known.

2024-11-24 05:41 UTC, pconrad commented on frontend/src/main/components/RecommendationRequest/RecommendationRequestForm.js
> +        </Col>
Unnecessary.   Requester id is stored in the backend.
```suggestion

```

2024-11-24 05:41 UTC, pconrad commented on frontend/src/main/components/RecommendationRequest/RecommendationRequestForm.js
> +        </Col>
```suggestion

```

2024-11-24 05:41 UTC, pconrad commented on frontend/src/main/components/RecommendationRequest/RecommendationRequestForm.js
> +        </Col>
Set requesterId in the backend.   That way you get access to both the name and email.  

```suggestion

```

2024-11-24 05:41 UTC, pconrad commented on frontend/src/main/components/RecommendationRequest/RecommendationRequestForm.js
> +        </Col>
No.
```suggestion
    {/* A dropdown component should go here, populated with all users that 
        have the Professsor flag set in the Users table.  Pass only the id of the selected
         professor to the backend.  From that, we can get the name and email of the professor */}
```

2024-11-24 05:41 UTC, pconrad commented on frontend/src/main/components/RecommendationRequest/RecommendationRequestForm.js
> +      </Row>
```suggestion

```

Not needed... see above.

2024-11-24 05:41 UTC, pconrad commented on frontend/src/main/components/RecommendationRequest/RecommendationRequestForm.js
> +        </Col>
```suggestion
   {/* Replace with Dropdown selector that shows all values in the RequestType table */}
```

No.  The whole point of having a RequestType database table is that the request types are NOT hard coded.   This should be a dropdown of values from that table.

2024-11-24 05:41 UTC, pconrad commented on frontend/src/main/components/RecommendationRequest/RecommendationRequestForm.js
> +        </Col>
No.   The submission date is calculated automatically in the backend.  The end user doesn't calculate it.

2024-11-24 05:41 UTC, pconrad commented on frontend/src/main/components/RecommendationRequest/RecommendationRequestForm.js
> +        </Col>
No.  Completion date is entered automatically in the backend LATER when the professor actually marks the request as complete.

However, we probably SHOULD have a "neededByDate", and this selector could be repurposed for that.  That would need to be added to the fixtures as well as to the entity and database migration files.

2024-11-24 05:41 UTC, pconrad commented on frontend/src/tests/components/RecommendationRequest/RecommendationRequestForm.test.js
> +
Adjust test after adjusting form as described above.

2024-11-27 19:16 UTC, pconrad approved these changes
ooops... the comment I previously typed was put on the wrong PR.

2024-11-27 19:22 UTC, closed without merging

2024-11-27 19:22 UTC, pconrad commented
<img width="317" alt="image" src="https://github.com/user-attachments/assets/47c9d4fc-6bf2-4c3c-86d9-3c3c52c88889">